### ISSUE TITLE
Build button doesn't highlight

### ISSUE THREAD

**Issue by LinJonKur** [XFactHD/RecipeBuilder#1]
As the tile says, the build button doesn't work in any way on version 1.16.5

**Comment by XFactHD** [comment]
Which recipe type are you trying to generate?
Did you set an unlock criteria?

You need to be far more specific for me to be able to help you. A screenshot of the UI when you expect the build button to be active would be useful too.

**Comment by XFactHD** [comment]
Closing due to lack of feedback.
If you decide to provide the necessary information at a later time, feel free to comment on this issue and I will reopen it if needed.

**Comment by EXFrost** [comment]
I have tried the mod on 1.16.5 also and faced the same issue, the build button is greyed out on all options so the mod is completely unusable and also any other buttons i try to press on the screen also do nothing

**Comment by XFactHD** [comment]
Please read my response to the OP, you need to provide more details as mentioned.

**Comment by EXFrost** [comment]
https://imgur.com/a/gF4Ko2g
the build button is always greyed and all other buttons on the left are irresponsive when clicked other than reset

**Comment by EXFrost** [comment]
*right sorry
left works all fine

**Comment by XFactHD** [comment]
You need to set an unlock condition.
If the "Set condition" button does nothing, then I need to see the log as it might be throwing an exception. Please put your debug log on https://gist.github.com

**Comment by EXFrost** [comment]
how do I find said log

**Comment by XFactHD** [comment]
In the game directory (%APPDATA%/.minecraft when you are playing with the vanilla launcher on Windows) there is a log folder which contains a latest.log and a debug.log file (if you have file extensions disabled, they will just be called "latest" and "debug"). If you are using a third-party launcher, then you will have to find out where the game directory for it is.

**Comment by EXFrost** [comment]
ye i knew where they were but which ones do i use

**Comment by XFactHD** [comment]
The file called "debug.log". If there are multiple files called "debug.log" and one just called "debug", then you have file extensions disabled and the file you want is the one called "debug".

**Comment by EXFrost** [comment]
https://gist.github.com/EXFrost/bca2437af616182ab801e7da519058de

**Comment by XFactHD** [comment]
The log doesn't show anything wrong.
What happens when you click the "Set condition" button?
Please also try reproducing this without OptiFine.

**Comment by EXFrost** [comment]
ah so ive removed all my mods and it works fine so im gonna go through to see which mod is messing with it

**Comment by EXFrost** [comment]
ye i think its optifine

**Comment by XFactHD** [comment]
Then there is nothing I can do about that due to OptiFine being closed source.
My suspiccion is that they break the GUI layering system in Forge. I would suggest reporting this to OptiFine.

**Comment by EXFrost** [comment]
actually after removing optifine which messed with the mod, after getting back all my mods its still acting incorrectly so maybe another mod is conflicting with it too
