### ISSUE TITLE
Is there a way to apply this to my servers?

### ISSUE THREAD

**Issue by amsmartrobber** [XFactHD/RecipeBuilder#13]
And If so, where do I put it in my server? What file?

**Comment by XFactHD** [comment]
The mod generates a datapack that is ready to use. To do so, go into the `recipebuilder` folder in your game folder (the folder that also contains the `resourcepacks`, `saves` and `configs` folders) and either copy the entire `generated_datapack` folder or make a ZIP file from its contents and copy that and place either the folder or the ZIP in the `datapacks` folder of the server's world.

The confirmation screen that opens when a recipe was generated also provides the path to that generated datapack folder which you can click on to directly open the `generated_pack` folder.

See the Minecraft wiki for more details on how to install datapacks: https://minecraft.fandom.com/wiki/Data_pack.

**Comment by amsmartrobber** [comment]
> The mod generates a datapack that is ready to use. To do so, go into the `recipebuilder` folder in your game folder (the folder that also contains the `resourcepacks`, `saves` and `configs` folders) and either copy the entire `generated_datapack` folder or make a ZIP file from its contents and copy that and place either the folder or the ZIP in the `datapacks` folder of the server's world.
> 
> The confirmation screen that opens when a recipe was generated also provides the path to that generated datapack folder which you can click on to directly open the `generated_pack` folder.
> 
> See the Minecraft wiki for more details on how to install datapacks: https://minecraft.fandom.com/wiki/Data_pack.

Thank you!

**Comment by amsmartrobber** [comment]
All finished!
