### ISSUE TITLE
Recipes only by world

### ISSUE THREAD

**Issue by YzXupoo** [XFactHD/RecipeBuilder#2]
I am creating a mod pack and I have found a slight issue. I have altered and added recipes to the game but when I or anyone else starts a new world the recipes convert back to the way they were and the new ones are not seen at all. Please let me know what files you need. If this is the intended use for this mod please let me know. Thank you.

**Comment by XFactHD** [comment]
RecipeBuilder generates the datapack in two places:
- Within the world you are currently in, this is intended for testing the new recipes without any copying
- In the root directory of the game instance in a folder called `recipebuilder` (see screenshot), this export is intended to be copied to the target world or published. This datapack is called `generated_pack`

Keep in mind that RecipeBuilder generates standard Minecraft datapacks, which means they are also subject to the limitations of that system. This means that, by default, you need to copy the generated datapack to the datapacks folder of the world after creating it. If you want to apply the datapack to every newly created world, then you need to use a mod that adds a "global datapack" system, like [Global Data- & Resourcepacks by JTK222](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack)

Location of the second export:
![grafik](https://user-images.githubusercontent.com/11262040/166458721-e1c583e9-b220-42f8-bdf2-e42a0130f75b.png)

I'll keep the issue open in case you have further questions.

**Comment by YzXupoo** [comment]
Thank you. I have solved the issue. I appreciate the recommendation of the mod for the solution. It was very helpful. You did a good job on the mod and so did the recommended mod. Thank you again.

**Comment by XFactHD** [comment]
Thank you for the feedback, I'll close the issue as solved.

**Comment by MokahTGS** [comment]
**Thumbs up**

This is super helpful!
