### ISSUE TITLE
[Question] Modpack Usage

### ISSUE THREAD

**Issue by MokahTGS** [XFactHD/RecipeBuilder#7]
I'm using this mod in my modpack Cosmic Magitech and was wondering when I export the recipes to a datapack, if I need to include the RecipeBuilder folder with the CF modpack files or can I just include the datapack that I've made.  Also, do even have to include the Recipe Builder mod with the modpack for my recipes to work?  

I have other mods that load datapacks out of the resourcepack folder so they are used in any new world that is made with the modpack.

**Comment by XFactHD** [comment]
You only need the datapack. The `recipebuilder` folder it is placed in is just to separate the datapack from anything other mods may place in the game folder. The mod itself does also not need to be included in the modpack unless you want to give your users the option to make recipes.

**Comment by MokahTGS** [comment]
Great, thx for the clarification!
