### ISSUE TITLE
How Does It Work

### ISSUE THREAD

**Issue by Caldeiradas** [XFactHD/RecipeBuilder#9]
The mod seems easy and intuitive and it has all the explanations except: **How to start using the mod**.  

I tried `/give` for any block to trigger the UI, I tried `/recipebuiler` and I have nothing, no UI, no way to add or fix recipes. I even tried to find anything in the Pack Folder but had no luck.  
Can that you help?  

Thank you!

**Comment by XFactHD** [comment]
The recipe and tag builder UIs are opened with the B and V key respectively. You can find those keybinds in the controls settings.

**Comment by Caldeiradas** [comment]
Thank you!

Had to change the keys and functions 100% now. Thank you!

Ps.: Do you know or have any mod like this for costume villager trades? Tks ;)

**Comment by XFactHD** [comment]
Villager trades can currently not be controlled by JSON files in the base game. The only thing that comes to my mind as an option is KubeJS, they might have a feature that allows adding custom trades.
